version: "3"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    links:
      - mongodb:mongodb
  mongodb:
    image: "mongo:3"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: realtime_chat
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro