basePath: /realtime-chat/api/v1
definitions:
  dto.ErrorMessage:
    properties:
      description:
        type: string
      message:
        type: string
    type: object
  dto.SuccessMessage:
    properties:
      id:
        type: object
      message:
        type: string
    type: object
  model.ChatRoom:
    properties:
      _id:
        type: string
      name:
        type: string
    type: object
  model.Message:
    properties:
      _id:
        type: string
      body:
        type: string
      chatroom_id:
        type: string
      user_id:
        type: string
    type: object
  model.User:
    properties:
      _id:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: This microservice serves as Realtime chat backend
  title: RealTime-Chat Microservice
  version: "1"
paths:
  /chat-rooms:
    post:
      description: Create new user and saves in mongo db
      parameters:
      - description: Request body has user details
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/dto.SuccessMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Create new user API
  /messages:
    post:
      description: Create new message and saves in mongo db
      parameters:
      - description: Request body has message details
        in: body
        name: Message
        required: true
        schema:
          $ref: '#/definitions/model.Message'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/dto.SuccessMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Create new message API
swagger: "2.0"
